import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Learning Next App",
    template: "%s | Learning Next App",
  },
  keywords: ["NextJs", "React", "JS", "Asia Cup"],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar></Navbar>
        <main className="h-screen h-max-[800px]">{children}</main>
        <footer className="text-gray-600 text-center">
          Awesome NEXTJS Project
        </footer>
      </body>
    </html>
  );
}
